version = 1

test_patterns = ["test/**"]

exclude_patterns = [
    ".github/**",
    "doc/**"
]

[[analyzers]]
name = "javascript"
enabled = true

  [analyzers.meta]
  environment = ["nodejs"]
  style_guide = "airbnb"